import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vite-plus";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// Tauri exposes these when driving Vite (mobile dev / remote HMR). Absent in
// plain `vp dev` and in CI, so every read is guarded.
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig({
  // src/ipc/bindings.ts is generated by tauri-specta (crates/desktop's
  // export_bindings test); its shape is owned by the generator, so keep oxfmt and
  // oxlint off it. It stays type-checked by `tsc -b` (with a generated-file
  // `// @ts-nocheck` header the generator step adds).
  fmt: {
    ignorePatterns: ["src/ipc/bindings.ts"],
  },
  lint: {
    ignorePatterns: ["src/ipc/bindings.ts"],
    plugins: ["react", "typescript", "oxc"],
    rules: {
      "react/rules-of-hooks": "error",
      "react/only-export-components": [
        "warn",
        {
          allowConstantExport: true,
        },
      ],
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
  },
  plugins: [react(), tailwindcss()],

  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },

  // Tauri expects a fixed dev port and never garbles the console it wraps.
  clearScreen: false,
  server: {
    port: 5173,
    strictPort: true,
    host: host ?? false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // Tauri source lives outside frontend/; no reason to watch it.
      ignored: ["**/src-tauri/**"],
    },
  },

  // Only VITE_ and TAURI_ENV_* vars are exposed to the client bundle.
  envPrefix: ["VITE_", "TAURI_ENV_"],

  build: {
    // Match the webview each target platform ships; Windows/WebView2 tracks
    // Chrome, macOS tracks Safari. Falls back to a modern baseline for `vp dev`.
    target: process.env.TAURI_ENV_PLATFORM === "windows" ? "chrome105" : "safari13",
    // Debug builds keep readable output; release minifies. MUST be "oxc": the
    // vp/rolldown toolchain ships no esbuild — "esbuild" only appeared to work
    // on vite-plus 0.1.24 because its esbuild-transpile plugin is gated off by
    // the rolldown default `esbuild: false`; newer cores hard-error and demand
    // a separately-installed esbuild.
    minify: process.env.TAURI_ENV_DEBUG ? false : "oxc",
    sourcemap: !!process.env.TAURI_ENV_DEBUG,
  },

  test: {
    // jsdom lacks WebCrypto, which @tauri-apps/api's mockIPC transport needs.
    environment: "happy-dom",
    globals: true,
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    setupFiles: ["./src/test/setup.ts"],
  },
});
