//! Compositz desktop backend (Tauri 2).
//!
//! The IPC surface is the Rust port of the Deno `routes/api/*` handlers, exposed as
//! tauri commands whose TypeScript bindings are generated by `tauri-specta` from the
//! SAME Rust types core already defines — one source of truth for every shape. This
//! crate links webkit2gtk/dbus and so compiles only in CI (windows-latest) / on a
//! desktop OS, never in the headless dev container; it is validated locally by
//! `cargo metadata` + review, and by the core-side tests behind its logic.

mod commands;
mod error;
mod state;

use compositz_core::connect;
use compositz_core::storage::{HostPlatform, instances_dir};
use state::AppState;
use tauri::Manager;
use tauri_specta::{Builder, collect_commands};

/// The tauri-specta command registry. Listing the commands ONCE here keeps the
/// invoke handler and the generated TypeScript bindings in lockstep — adding a
/// command in one place cannot drift from the other.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::list_instance_rows,
        commands::instance_up,
        commands::instance_down,
        commands::instance_delete,
        commands::instance_duplicate,
        commands::get_config,
        commands::set_config,
        commands::import_recipe,
        commands::import_github,
        commands::export_mount,
        commands::open_service_url,
    ])
}

/// Build and run the Tauri application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    // Regenerate the frontend's typed bindings on every dev run (never in release).
    // A runtime `cfg!` (not `#[cfg]`) so the export code is still COMPILED in the
    // release artifact build — the only CI job that builds this crate — and cannot
    // silently rot; it just doesn't run outside a debug build.
    if cfg!(debug_assertions) {
        builder
            .export(
                specta_typescript::Typescript::default(),
                "../../frontend/src/ipc/bindings.ts",
            )
            .expect("export typescript bindings");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            // Required for tauri-specta events (added with the streaming commands).
            builder.mount_events(app);
            // Connect to the engine + resolve the store at startup. A failure here is
            // fatal for now (a manager with no engine can do nothing); a later phase
            // can degrade to a connection banner.
            let engine = connect()?;
            let store = instances_dir(&HostPlatform)?;
            app.manage(AppState { engine, store });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Compositz");
}
