//! Compositz desktop backend (Tauri 2).
//!
//! The IPC surface is exposed as tauri commands whose TypeScript bindings are
//! generated by `tauri-specta` from the SAME Rust types core already defines — one
//! source of truth for every shape. This crate links webkit2gtk/dbus, so locally it
//! needs the nix devShell (`nix develop -c cargo …`, see flake.nix); CI
//! windows-latest builds the installers.

mod commands;
mod error;
mod state;
mod stream;

use std::sync::Mutex;

use compositz_core::connect;
use compositz_core::storage::{HostPlatform, instances_dir};
use state::{AppState, StreamRegistry};
use tauri::{Manager, WindowEvent};
use tauri_specta::{Builder, collect_commands};

/// The tauri-specta command registry. Listing the commands ONCE here keeps the
/// invoke handler and the generated TypeScript bindings in lockstep — adding a
/// command in one place cannot drift from the other. `pub` solely for the
/// `export_bindings` integration test (tests/), which regenerates the committed
/// frontend bindings from this same registry.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        // request/response
        commands::list_instance_rows,
        commands::instance_up,
        commands::instance_down,
        commands::instance_delete,
        commands::instance_duplicate,
        commands::rename_instance,
        commands::update_prepare,
        commands::update_commit,
        commands::update_discard,
        commands::get_config,
        commands::set_config,
        commands::import_recipe,
        commands::import_github,
        commands::export_mount,
        commands::open_service_url,
        // push streams (over tauri::ipc::Channel)
        stream::subscribe_instances,
        stream::stream_logs,
        stream::instance_install,
        stream::unsubscribe,
    ])
}

/// Build and run the Tauri application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        // single-instance MUST be registered FIRST — its guard aborts a second
        // launch before the rest of setup runs; a second launch focuses the
        // existing window instead of opening another engine connection.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_log::Builder::new().build())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .on_window_event(|window, event| {
            // Window teardown stops every live pump so none outlives the webview.
            if matches!(event, WindowEvent::Destroyed)
                && let Some(state) = window.try_state::<AppState>()
            {
                state
                    .streams
                    .lock()
                    .expect("stream registry mutex poisoned")
                    .abort_all();
            }
        })
        .setup(move |app| {
            // Required for tauri-specta events (in addition to the command handler).
            builder.mount_events(app);
            // Connect to the engine + resolve the store at startup. A failure here is
            // fatal for now (a manager with no engine can do nothing); a later phase
            // can degrade to a connection banner.
            let engine = connect()?;
            let store = instances_dir(&HostPlatform)?;
            app.manage(AppState {
                engine,
                store,
                streams: Mutex::new(StreamRegistry::default()),
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Compositz");
}
