//! Compositz desktop backend (Tauri 2).
//!
//! The IPC surface is the Rust port of the Deno `routes/api/*` handlers, exposed as
//! tauri commands whose TypeScript bindings are generated by `tauri-specta` from the
//! SAME Rust types core already defines — one source of truth for every shape. This
//! crate links webkit2gtk/dbus and so compiles only in CI (windows-latest) / on a
//! desktop OS, never in the headless dev container; it is validated locally by
//! `cargo metadata` + review, and by the core-side tests behind its logic.

mod commands;
mod error;
mod state;
mod stream;

use std::sync::Mutex;

use compositz_core::connect;
use compositz_core::storage::{HostPlatform, instances_dir};
use state::{AppState, StreamRegistry};
use tauri::{Manager, WindowEvent};
use tauri_specta::{Builder, collect_commands};

/// The tauri-specta command registry. Listing the commands ONCE here keeps the
/// invoke handler and the generated TypeScript bindings in lockstep — adding a
/// command in one place cannot drift from the other.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        // request/response
        commands::list_instance_rows,
        commands::instance_up,
        commands::instance_down,
        commands::instance_delete,
        commands::instance_duplicate,
        commands::get_config,
        commands::set_config,
        commands::import_recipe,
        commands::import_github,
        commands::export_mount,
        commands::open_service_url,
        // push streams (over tauri::ipc::Channel)
        stream::subscribe_instances,
        stream::stream_logs,
        stream::instance_install,
        stream::unsubscribe,
    ])
}

/// Build and run the Tauri application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        // single-instance MUST be registered FIRST — its guard aborts a second
        // launch before the rest of setup runs; a second launch focuses the
        // existing window instead of opening another engine connection.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_log::Builder::new().build())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .on_window_event(|window, event| {
            // Window teardown stops every live pump so none outlives the webview.
            if matches!(event, WindowEvent::Destroyed)
                && let Some(state) = window.try_state::<AppState>()
            {
                state
                    .streams
                    .lock()
                    .expect("stream registry mutex poisoned")
                    .abort_all();
            }
        })
        .setup(move |app| {
            // Required for tauri-specta events (in addition to the command handler).
            builder.mount_events(app);
            // Connect to the engine + resolve the store at startup. A failure here is
            // fatal for now (a manager with no engine can do nothing); a later phase
            // can degrade to a connection banner.
            let engine = connect()?;
            let store = instances_dir(&HostPlatform)?;
            app.manage(AppState {
                engine,
                store,
                streams: Mutex::new(StreamRegistry::default()),
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Compositz");
}

#[cfg(test)]
mod tests {
    /// Regenerate the frontend's typed IPC bindings from the SAME commands the
    /// app registers — the canonical tauri-specta workflow, run as a test so it
    /// is reproducible in the Nix build shell where this crate compiles (the
    /// headless dev container cannot link webkit outside that shell) and so CI
    /// can assert the committed bindings are fresh.
    #[test]
    fn export_bindings() {
        let path = "../../frontend/src/ipc/bindings.ts";
        super::specta_builder()
            .export(specta_typescript::Typescript::default(), path)
            .expect("export typescript bindings");

        // tauri-specta rc.21 emits, for a Channel-carrying command surface, a
        // `TAURI_CHANNEL` placeholder type that collides with the imported
        // `Channel as TAURI_CHANNEL` (TS2440), plus event scaffolding we never
        // reference (we push over Channels, not tauri events). Drop the colliding
        // placeholder so `TAURI_CHANNEL` unambiguously means the imported Channel
        // for consumers, and prepend `// @ts-nocheck` so `noUnusedLocals` does not
        // trip on the leftover generated scaffolding. The frontend also excludes
        // this file from fmt/lint (see vite.config.ts) — its shape is the
        // generator's, not ours.
        let generated = std::fs::read_to_string(path).expect("read generated bindings");
        let body: String = generated
            .lines()
            .filter(|line| line.trim() != "export type TAURI_CHANNEL<TSend> = null")
            .collect::<Vec<_>>()
            .join("\n");
        std::fs::write(path, format!("// @ts-nocheck\n{body}\n")).expect("write cleaned bindings");
    }
}
