// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * The initial dashboard: every stored instance as a row, joined with a live engine
 * read (running + installed). When the engine is unreachable the rows still list
 * (installed unknown, nothing running). The live/probed updates arrive over
 * `subscribe_instances`.
 */
async listInstanceRows() : Promise<Result<InstanceRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_instance_rows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bring an instance up: build the image if it is missing (drained silently — the
 * explicit build-with-log path is `instance_install`), create + start, and return
 * the published web URL.
 */
async instanceUp(id: string) : Promise<Result<UpView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("instance_up", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop + remove an instance's container. The id is validated at the boundary before
 * it reaches the engine op (every command that accepts an instance id MUST do so).
 */
async instanceDown(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("instance_down", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop + remove the container, the per-instance built image, and (by default) the
 * per-instance DATA VOLUMES; then the definition. A load of the (best-effort)
 * definition precedes removal so the image tag + volume names are known; a missing
 * definition still gets its dir removed.
 */
async instanceDelete(id: string, opts: DeleteOpts) : Promise<Result<DeleteView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("instance_delete", { id, opts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Derive a fresh instance from an existing one (copies the bundle + Settings
 * override minus ports; data starts empty), deconflict its DEFINED ports, and
 * return the finished view + bumps.
 */
async instanceDuplicate(id: string) : Promise<Result<ImportView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("instance_duplicate", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set or clear the per-instance display name (`meta.name`). `None` — or a name
 * that trims to empty / equals the manifest brand — clears the override, so the
 * display returns to tracking the manifest name. Core re-validates the id at the
 * path-touching sink; the row list reflects the change on the next fetch.
 */
async renameInstance(id: string, name: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_instance", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Settings view-model for an instance: each manifest port/env/mount with its
 * author default + saved override, plus the host ports DEFINED by OTHER instances
 * and whether a restart is needed.
 */
async getConfig(id: string) : Promise<Result<InstanceSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate an override (value ranges + keys must name manifest items) and persist
 * it to `config.yaml`; it takes effect on the next `up`.
 */
async setConfig(id: string, over: Override) : Promise<Result<SetConfigView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { id, over }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a recipe bundle from a local path (a tar / tar.gz archive file or a
 * directory) into a new instance, then deconflict its host ports. The frontend
 * picks the path via the dialog plugin.
 */
async importRecipe(source: string) : Promise<Result<ImportView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_recipe", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a recipe from a GitHub source spec (`owner/repo[/subdir][@ref]`, optional
 * `github:` prefix), download + ingest it, then deconflict. Public repos only.
 */
async importGithub(spec: string) : Promise<Result<ImportView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_github", { spec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export one persisted mount's data as a tar written to `dest` (the frontend picks
 * `dest` via the dialog plugin). Works on a stopped instance (a throwaway helper
 * reads the data).
 */
async exportMount(id: string, mount: string, dest: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_mount", { id, mount, dest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a LOCAL web-service URL in the OS default browser via the opener plugin.
 * Locked down: only http(s) localhost URLs, passed as a direct arg (the plugin
 * never shells out), so neither command injection nor an arbitrary opener
 * (file://, app protocols, remote hosts) is possible.
 */
async openServiceUrl(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_service_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Subscribe to managed-container snapshots. Returns a subscription id; the pump runs
 * until `unsubscribe(id)`, window teardown, or the receiver is dropped.
 */
async subscribeInstances(onEvent: TAURI_CHANNEL<SnapshotEvent>) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_instances", { onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stream a RUNNING container's logs (validated id → container name). Returns a
 * subscription id.
 */
async streamLogs(id: string, onLog: TAURI_CHANNEL<LogEvent>) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_logs", { id, onLog }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build (or pull) an instance's image, streaming the build log. Returns a
 * subscription id.
 */
async instanceInstall(id: string, onProgress: TAURI_CHANNEL<InstallEvent>) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("instance_install", { id, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a subscription's pump (idempotent). Called on tab close / component unmount.
 */
async unsubscribe(subscriptionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unsubscribe", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { kind: "badRequest"; message: string } | { kind: "internal"; message: string }
/**
 * A managed container reduced to what the dashboard needs — `instance` is the
 * instance id carried by the container label (`None` if absent); `state` is
 * Docker's container state; `ports` are the host-published bindings.
 */
export type ContainerStatus = { instance: string | null; state: string; ports: PublishedPort[] }
/**
 * Delete options: remove the data volumes, and the host-browsable bind data.
 */
export type DeleteOpts = { volumes: boolean; bindData: boolean }
/**
 * The outcome of a delete: a non-fatal partial-outcome warning, if any (host data
 * left behind, unreadable definition). A hard failure is an `AppError` instead.
 */
export type DeleteView = { warning: string | null }
/**
 * One manifest env var in the Settings editor.
 */
export type EnvSetting = { name: string; description?: string | null; required: boolean; 
/**
 * Manifest default / placeholder value.
 */
default?: string | null; 
/**
 * Saved value override, if any.
 */
override?: string | null }
/**
 * A freshly-created instance for the trust prompt: the view plus any host-port
 * reassignments to disclose. Shared by import (file + GitHub) and duplicate.
 */
export type ImportView = { view: InstanceView; bumps: PortBump[] }
/**
 * One line of build output, the built image tag on success, or an error.
 */
export type InstallEvent = { type: "log"; line: string } | { type: "done"; tag: string } | { type: "error"; error: string }
/**
 * One rendered dashboard row: an instance plus its derived runtime status.
 */
export type InstanceRow = { instanceId: string; appId: string; name: string; version: string; description: string; 
/**
 * Provenance: where the bundle came from (`meta.json` `source`), if recorded.
 */
source?: string | null; 
/**
 * Provenance: ISO-8601 creation time (`meta.json` `createdAt`), if recorded.
 */
createdAt?: string | null; webPorts: WebPort[]; 
/**
 * Declared services, always listed from the definition; the live port fills in
 * when running.
 */
services: Service[]; 
/**
 * Image built locally? `None` when the engine is unreachable (unknown).
 */
installed: boolean | null; 
/**
 * A managed container for this instance is in the "running" state.
 */
running: boolean }
/**
 * The Settings editor view-model for one instance (manifest ⊕ saved override).
 */
export type InstanceSettings = { ports: PortSetting[]; env: EnvSetting[]; mounts: MountSetting[]; 
/**
 * Host ports DEFINED by OTHER instances — the client checks port conflicts
 * against this (definition-based, so it catches stopped instances).
 */
takenByOthers: number[]; 
/**
 * The saved config has diverged from what the running instance was launched with.
 */
restartNeeded: boolean }
/**
 * An instance reduced to the fields the dashboard renders.
 */
export type InstanceView = { 
/**
 * The runtime key — actions and status match on this.
 */
instanceId: string; 
/**
 * The app (manifest id) this instance runs — a slug, for display/grouping.
 */
appId: string; name: string; version: string; description: string; 
/**
 * Provenance: where the bundle came from (`meta.json` `source`), if recorded.
 */
source?: string | null; 
/**
 * Provenance: ISO-8601 creation time (`meta.json` `createdAt`), if recorded.
 */
createdAt?: string | null; 
/**
 * Declared web ports (`web: true`). Live URLs are resolved against the container.
 */
webPorts: WebPort[]; 
/**
 * The image tag this instance builds to (e.g. `compositz/hello-a1b2c3:0.1.0`).
 */
imageTag: string }
/**
 * One line of a container's logs, the end-of-stream marker, or an error. (Core's
 * `log_stream` yields already-demuxed lines, so there is no per-line stdout/stderr
 * tag.)
 */
export type LogEvent = { type: "log"; line: string } | { type: "end" } | { type: "error"; error: string }
/**
 * One manifest mount in the Settings editor (placement is the only override).
 */
export type MountSetting = { name: string; target: string; description?: string | null; manifestPlacement: Placement; override?: Placement | null }
/**
 * The persisted per-instance override — a strict subset of `run.rs`'s launch config.
 * Crosses the IPC boundary as the `set_config` INPUT, so it is a `specta::Type`.
 */
export type Override = { 
/**
 * Host-port remap, keyed by port `name`.
 */
hostPorts?: Partial<{ [key in string]: number }> | null; 
/**
 * Env value override, keyed by env `name`.
 */
env?: Partial<{ [key in string]: string }> | null; 
/**
 * Placement override, keyed by mount `name`.
 */
placement?: Partial<{ [key in string]: Placement }> | null }
export type Placement = "bind" | "volume"
/**
 * A host port reassigned away from a collision: `name`'s desired `from` → `to`.
 * Serialized to the desktop trust prompt (which notifies the user of any
 * reassignment), so it crosses the IPC boundary as a `specta::Type`.
 */
export type PortBump = { name: string; from: number; to: number }
/**
 * One manifest port in the Settings editor: author default + saved override.
 */
export type PortSetting = { name: string; container: number; web: boolean; description?: string | null; 
/**
 * Manifest default host port (`p.host ?? p.container`).
 */
manifestHost: number; 
/**
 * Saved host-port override, if any.
 */
override?: number | null }
/**
 * A container port that the engine has actually published to the host.
 */
export type PublishedPort = { container: number; public: number; protocol: string; 
/**
 * The app behind the port ACCEPTS an HTTP request (server-side probe). Docker
 * publishes the mapping the moment the container starts — minutes before a
 * heavy AI app listens — so `ready` requires an explicit `Some(true)` (a
 * missing probe degrades to "starting…", never to a false "ready").
 */
accepting?: boolean | null }
/**
 * A declared web endpoint resolved to a host port (live published ▷ defined), with
 * `ready` gated on the probe.
 */
export type Service = { name: string; path: string; description?: string | null; 
/**
 * Host port: live published ▷ defined (override ▷ manifest).
 */
port: number; 
/**
 * Openable URL built from `port` + path.
 */
url: string; 
/**
 * The live binding is confirmed in `ps` AND the app answered the probe.
 */
ready: boolean }
/**
 * The result of saving a config override: whether a restart is needed to apply it.
 */
export type SetConfigView = { restartNeeded: boolean }
/**
 * A managed-container snapshot push, or an engine-offline notice.
 */
export type SnapshotEvent = { type: "snapshot"; containers: ContainerStatus[] } | { type: "offline"; error: string }
/**
 * The result of bringing an instance up.
 */
export type UpView = { id: string; usedGpu: boolean; 
/**
 * The primary web UI URL, if the recipe publishes one (built from the ports
 * ACTUALLY published after any conflict bump).
 */
url: string | null }
/**
 * A manifest port that serves a browser UI (`web: true`). An app may declare many.
 */
export type WebPort = { 
/**
 * Stable port name (label + override key).
 */
name: string; 
/**
 * Port inside the container — joined to a running container's published port.
 */
container: number; protocol: string; 
/**
 * Absolute UI path appended to the URL.
 */
path: string; 
/**
 * Effective DEFINED host port (override ▷ manifest host ▷ container) — the
 * fallback when no live published port is known yet.
 */
host: number; description?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
